### ISSUE TITLE
邮箱识别有问题

### ISSUE THREAD

**Issue by Cyl18** [HimitZH/HOJ#1]
前端所用正则不能识别域名后缀有4个字母的..
![image](https://user-images.githubusercontent.com/14993992/132274068-43bdf3d6-7e44-4fd3-8cb9-4e3696a7a1d2.png)

代码位置
https://github.com/HimitZH/HOJ/blob/b1ee8769edc092a83d4ee0149c250030d08a3028/hoj-vue/src/components/oj/common/Register.vue#L227

可以使用这里的正则
https://github.com/dromara/hutool/blob/c36f9f55db1c271966863c1dd397a9f29678e837/hutool-core/src/main/java/cn/hutool/core/lang/RegexPool.java#L51

**Comment by HimitZH** [comment]
> 前端所用正则不能识别域名后缀有4个字母的..
> ![image](https://user-images.githubusercontent.com/14993992/132274068-43bdf3d6-7e44-4fd3-8cb9-4e3696a7a1d2.png)
> 
> 代码位置
> 
> https://github.com/HimitZH/HOJ/blob/b1ee8769edc092a83d4ee0149c250030d08a3028/hoj-vue/src/components/oj/common/Register.vue#L227
> 
> 可以使用这里的正则
> https://github.com/dromara/hutool/blob/c36f9f55db1c271966863c1dd397a9f29678e837/hutool-core/src/main/java/cn/hutool/core/lang/RegexPool.java#L51

**Comment by HimitZH** [comment]
好的 谢谢提醒。
