### ISSUE TITLE
建议添加一个执行代码的按钮

### ISSUE THREAD

**Issue by xiaonian233** [HimitZH/HOJ#10]
不知道这个想法是否可行，类似于力扣那种提交代码旁边有个执行代码，可以来测试用例。如果不行就请忽略，谢谢。

**Comment by HimitZH** [comment]
当然行，前端难写 = =

**Comment by xiaonian233** [comment]
好的谢谢作者，我自己再研究吧

**Comment by HimitZH** [comment]
> 好的谢谢作者，我自己再研究吧

最新版的HOJ已有 这个功能了 也就是在线自测功能 可以到hdoi.cn体验
