### ISSUE TITLE
登录的账号和实际登上的号不是同一个

### ISSUE THREAD

**Issue by miaostudy** [HimitZH/HOJ#16]
比如我登root，点开我的首页显示的是别人的首页，提交记录啥的也全是别人的。刚部署完这个问题不是很频繁，最近几乎每次隔一段时间重新进入网站都会出现点开首页是别人或者显示uid不能为空（这个估计是因为别人串到我的账号上去了，所以我这进来再看首页就是空的），重新登录得过两分钟才恢复正常，求问大佬这个可能是因为什么原因，该怎么调，最近几乎每个人隔一段时间就会串，每次进都得重新登录等两分钟

**Comment by HimitZH** [comment]
一个浏览器只能有一个账号登录

**Comment by miaostudy** [comment]
> 一个浏览器只能有一个账号登录

呆
我们都登的自己号，但是登上去是别人的号 如果所有人都退出登录再重新登自己号会不会就正常了

**Comment by HimitZH** [comment]
可以试着更新到最新试试，我加了一个浏览器强一致同步登录账号信息，同样也是一个浏览器进程不论多少个标签页都只能同时一个用户

**Comment by miaostudy** [comment]
> 可以试着更新到最新试试，我加了一个浏览器强一致同步登录账号信息，同样也是一个浏览器进程不论多少个标签页都只能同时一个用户
佬更新完试了下仍然会串线
![SSBSU9{620) (DMIK9UGTV6](https://user-images.githubusercontent.com/93194540/192096095-c3abdff5-c020-4bb0-8f5d-113555403776.png)
测了一下，具体情况是一个人已经登录了自己的账号，与此同时另外一个人进行登录操作，已经登录上的人的首页就会变成另一个人的
或者是多个人同时登录也可能这样

**Comment by HimitZH** [comment]
> > 可以试着更新到最新试试，我加了一个浏览器强一致同步登录账号信息，同样也是一个浏览器进程不论多少个标签页都只能同时一个用户
> > 佬更新完试了下仍然会串线
> > ![SSBSU9{620) (DMIK9UGTV6](https://user-images.githubusercontent.com/93194540/192096095-c3abdff5-c020-4bb0-8f5d-113555403776.png)
> > 测了一下，具体情况是一个人已经登录了自己的账号，与此同时另外一个人进行登录操作，已经登录上的人的首页就会变成另一个人的
> > 或者是多个人同时登录也可能这样

不明白你的多个人同时登录是个啥玩意，都说一个浏览器只能有一个账号，可以刷新浏览器看看

**Comment by miaostudy** [comment]
> 

指很多用户在同一时间不同地方同时进行登陆操作

**Comment by HimitZH** [comment]
> > 
> 
> 指很多用户在同一时间不同地方同时进行登陆操作

不同电脑不同用户登录 应该是不同账号啊。你的指的串号是看的”我的首页“？你刷新看看也是一样？我就不信了 不同账号不同机器登录 还是相互串号，最好有完整截图或者视频演示

**Comment by miaostudy** [comment]
具体问题：
1. 很多人登自己号，登上了发现是别人的号，就是自己的账号密码登上了别人的号
2. 登上了自己的号，过一段时间会自己突然变成别人的号

**Comment by miaostudy** [comment]
> > > 
> > 
> > 
> > 指很多用户在同一时间不同地方同时进行登陆操作
> 
> 不同电脑不同用户登录 应该是不同账号啊。你的指的串号是看的”我的首页“？你刷新看看也是一样？我就不信了 不同账号不同机器登录 还是相互串号，最好有完整截图或者视频演示

谢谢，我联系xdm录视频

**Comment by HimitZH** [comment]
> 具体问题：
> 
> 1. 很多人登自己号，登上了发现是别人的号，就是自己的账号密码登上了别人的号
> 2. 登上了自己的号，过一段时间会自己突然变成别人的号

1. 这个有点扯淡，用自己账号登录别人的账号，逻辑上完全不通，从来没遇见过。
2. 过段时间变成别人的 更扯淡了，除非在机器上又登录过其他账号

**Comment by miaostudy** [comment]
> > 具体问题：
> > 
> > 1. 很多人登自己号，登上了发现是别人的号，就是自己的账号密码登上了别人的号
> > 2. 登上了自己的号，过一段时间会自己突然变成别人的号
> 
> 1. 这个有点扯淡，用自己账号登录别人的账号，逻辑上完全不通，从来没遇见过。
> 2. 过段时间变成别人的 更扯淡了，除非在机器上又登录过其他账号

我也觉得很离谱，从来没遇到过，所以才来请教的QAQ
串线之后无论是提交评测、发布讨论、榜单记录都是别人的信息，管理员的号串之后进后台会显示无权限。串之后之前从来没做过的题会显示您已做过（原号主ac过），如果此时ac原号主那会莫名其妙多出来一道ac

**Comment by HimitZH** [comment]
> > > 具体问题：
> > > 
> > > 1. 很多人登自己号，登上了发现是别人的号，就是自己的账号密码登上了别人的号
> > > 2. 登上了自己的号，过一段时间会自己突然变成别人的号
> > 
> > 
> > 
> > 1. 这个有点扯淡，用自己账号登录别人的账号，逻辑上完全不通，从来没遇见过。
> > 2. 过段时间变成别人的 更扯淡了，除非在机器上又登录过其他账号
> 
> 我也觉得很离谱，从来没遇到过，所以才来请教的QAQ 串线之后无论是提交评测、发布讨论、榜单记录都是别人的信息，管理员的号串之后进后台会显示无权限。串之后之前从来没做过的题会显示您已做过（原号主ac过），如果此时ac原号主那会莫名其妙多出来一道ac

在我看来，只可能是自己浏览器打开一个页面登录后，又另外新起一个页面进行另外账号的登录，然后又切回第一个页面，以为还是原账号，然后去交题，其实这时候就只能是后面重新的账号进行的交题，只不过是在页面上看得两个页面账号不一致，我说的更新就是为了解决这个页面显示问题，同样的是，**一个浏览器只会同一个账号进行操作，重新登陆就是用最新的账号！**

另外，除非能复现操作进行录屏 才能具体看到是为啥，反正我理解就是重复登录其他账号了。

**Comment by miaostudy** [comment]
刚刚尝试复现了一下，视频太大了发不出来，方便给个联系方式不

**Comment by miaostudy** [comment]
刚刚尝试复现了一下，不是很还原
mm是我的小号，第一个电脑操作的是我大号，原本是正常的，在小号登陆后首页变成了mm
https://user-images.githubusercontent.com/93194540/192098553-cc91a735-e3e4-4040-9d9e-1614d32ccdac.mp4


https://user-images.githubusercontent.com/93194540/192098711-1bde3bb6-1b96-439d-9261-40b4acb71a82.mp4

**Comment by HimitZH** [comment]
> 

更新到最新，然后再刷新浏览器复现看看，反正我没试出来

**Comment by HimitZH** [comment]
如果还有其它问题可以先加QQ群：598587305，这个issue我先关了
