### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 995509224** [HimitZH/HOJ#19]
你好大佬，我想请教一下如何进行输出文件与标答的比对，然后怎么用go-judge进行特判和交互题的，能帮我点一点思路吗，感激不尽

**Comment by HimitZH** [comment]
你应该去go-judge的项目问原作者

**Comment by 995509224** [comment]
> 你应该去go-judge的项目问原作者

大佬能给下您在遇到这几个问题的处理思路吗

**Comment by HimitZH** [comment]
> 

自己看代码呗
