### ISSUE TITLE
测试用例zip超过1M大小的话会上传失败

### ISSUE THREAD

**Issue by madhat386** [HimitZH/HOJ#26]
试了下压缩后的zip文件如果小于1M上传是正常的，超过就不行。不知道是否有地方可以设置，看了文档但是没找到这方面的信息。

**Comment by HimitZH** [comment]
很久没更新了？现在版本的文件上传最大限制是512M，也有可能是服务器带宽小，上传很慢，一直到请求超时了

**Comment by madhat386** [comment]
> 

嗯，我是在本地虚拟机上部署的最新版本，我也看了源码中设置的512M没错。但是本地测试也还是超过1M就失败，应该不是传输速度慢超时的问题

**Comment by madhat386** [comment]
> 很久没更新了？现在版本的文件上传最大限制是512M，也有可能是服务器带宽小，上传很慢，一直到请求超时了

查到原因了，是本地的nginx配置里少了client_max_body_size这个设置，限制了转发到后端的大小。感谢回复，打扰了
