### ISSUE TITLE
代码模板问题

### ISSUE THREAD

**Issue by csthenry** [HimitZH/HOJ#36]
前端显示不对啊，正常情况不是应该仅显示中间这部分吗？
![image](https://github.com/HimitZH/HOJ/assets/32993468/6eb95e4c-4408-46d4-9a5f-f4a55a9e5735)

**Comment by HimitZH** [comment]
只能单纯当成模板题功能，没做到像leetcode那样的函数题

**Comment by csthenry** [comment]
QDU是这个样子的，给前端返回的代码模板是中间那部分，之后判题的时候后端再把模板拼接了一下

**Comment by HimitZH** [comment]
是吧，但没有那样实现
