### ISSUE TITLE
关于CodeForces服务降级的提示

### ISSUE THREAD

**Issue by PythonSmall-Q** [HimitZH/HOJ#37]
开发者您好，我是Sean。
作为一名网络安全工程师，以及HOJ的忠实用户，我不得不提示您：CodeForces启用了Cloudflare的网络保护。这将会导致部分RemoteJudge出现提交失败和无法获取评测结果的情况。望知悉。
另：Atcoder和SPOJ目前尚未启用。但是我向他们的Dev Team了解，不排除启用自制的保护功能。

**Comment by PythonSmall-Q** [comment]
CodeForces的保护包括但不限于：自动机器人保护，流量监控，标头监控。

**Comment by HimitZH** [comment]
谢谢，早已知晓，开启Cloudflare后爬虫就失效了。
