### ISSUE TITLE
分布式判题服务的同步问题

### ISSUE THREAD

**Issue by csthenry** [HimitZH/HOJ#40]
咱们这个多个判题机是每100s拉取主服务rsync-master的**所有评测数据**？那主服务器带宽小点不是直接瘫掉了？
如果是这样同步数据的话，这操作有点吓人。。。

**Comment by PythonSmall-Q** [comment]
我在设想可不可以在需要的时候拉取数据，然后本机cache，1h没人用就直接delete。这样是不是就会好一点。
