### ISSUE TITLE
一个服务器在快速部署的情况下，再部署多个判题机

### ISSUE THREAD

**Issue by zhiguai** [HimitZH/HOJ#43]
貌似不可行，rsync-slave服务与rsync-master存在端口冲突

**Comment by HimitZH** [comment]
一台服务器不要部署多个判题机（因为都是共用cpu，没有说更多判题机更好的说法），而且rsync-slave服务与rsync-master是不同机器进行题目平常数据同步的工具，你单机要运行这两个干啥

**Comment by zhiguai** [comment]
😓好的
