### ISSUE TITLE
比赛开始前 管理员交的题目无法rejudge

### ISSUE THREAD

**Issue by beiyanpiki** [HimitZH/HOJ#5]
rt, 比赛开始前管理员提交的代码进行rejudge后, 会一直卡在pending. 而比赛中提交的代码则可以正常运行.

![image](https://user-images.githubusercontent.com/36980069/150633439-da03b243-dc07-4da2-aa7c-8c7f6291a2a3.png)

**Comment by HimitZH** [comment]
> rt, 比赛开始前管理员提交的代码进行rejudge后, 会一直卡在pending. 而比赛中提交的代码则可以正常运行.
> 
> ![image](https://user-images.githubusercontent.com/36980069/150633439-da03b243-dc07-4da2-aa7c-8c7f6291a2a3.png)

好的，已经定位到问题，主要是赛前提交没有纳入contest_record记录表，导致重判该赛前提交，数据不一致导致无法判题！目前已修复。
