### ISSUE TITLE
发现一个bug 当go-judge返回的exitStatus的值大于2147483647 会爆int导致异常处理的时候捕获不到 会抛出System.error

### ISSUE THREAD

**Issue by yzh-lh** [HimitZH/HOJ#52]
测试题目是https://loj.ac/p/100
测试时的代码是：
// import io, os
// input = io.BytesIO(os.read(0,os.fstat(0).st_size)).readline
// mod = 10**9+7
// n, p, m = [int(i) for i in input().split())]
// A = [[int(j) for j in input().split()] for i in range(n)]
// B = [[int(j) for j in input().split()] for i in range(p)]
// for i in range(n):
//     ri = [0]*m
//     for k in range(p):
//         s, bk = A[i][k], B[k]
//         for j in range(m):
//             ri[j] = (ri[j]+s*bk[j])%mod
//     print(*ri)
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

const long long MOD = 1000000007;
const long long T = MOD << 32;

int main() {
    long long n, p, m;
    cin >> n >> p >> m;
    long long A[n][p], B[p][m];

    for (long long i = 0; i < n; ++i)
        for (long long j = 0; j < p; ++j) {
            cin >> A[i][j];
            A[i][j] = (A[i][j] + T) % MOD;
        }

    for (long long i = 0; i < p; ++i)
        for (long long j = 0; j < m; ++j) {
            cin >> B[i][j];
            B[i][j] = (B[i][j] + T) % MOD;
        }

    for (long long i = 0; i < n; ++i) {
        long long ri[m];
        fill(ri, ri + m, 0);

        for (long long k = 0; k < p; ++k) {
            for (long long j = 0; j < m; ++j) {
                ri[j] += A[i][k] * B[k][j];
                ri[j] %= MOD;
            }
        }

        for (long long j = 0; j < m; ++j)
            cout << ri[j] << ' ';

        cout << endl;
    }

    return 0;
}

**Comment by HimitZH** [comment]
最新分支已经修复这个问题：[fc5f1b](https://github.com/HimitZH/HOJ/commit/15cb458a52ed702374beb6ac9a604e465afc5f1b)，使用`docker-compose pull`更新最新镜像后，`docker-compose up -d`重启服务即可

**Comment by yzh-lh** [comment]
好的

**Comment by yzh-lh** [comment]
好的
