### ISSUE TITLE
DataBackup重启后judgeToke未刷新

### ISSUE THREAD

**Issue by zalmon-sources** [HimitZH/HOJ#59]
每当重启DataBackup后，JudgeDispatcher的judgeToken（hoj.judge.token）值还是上一次的值，本次启动推送到nacos的新的judgeToken没有动态刷新，导致调用在线测评时，judgeServer端报：对不起！您使用的判题服务调用凭证不正确！访问受限！

**Comment by HimitZH** [comment]
理论上不会吧，judgeserver取的hoj.judge.token就是动态取的nacos上的配置，除非judgeserver与nacos链接断开了，或者读取的配置文件的环境不对
