### ISSUE TITLE
前端项目无法正常完成build

### ISSUE THREAD

**Issue by XY0797** [HimitZH/HOJ#62]
环境：

Node.js v20.15.0

npm@10.7.0

windows 11

使用淘宝源(https://registry.npmmirror.com)

问题现象：

`npm install`执行后一直转圈，无法安装

删除`hoj-vue/package-lock.json`后问题解决

运行`npm run build`

报错，详情见附件的`log.txt`

附件：

[log.txt](https://github.com/user-attachments/files/16129689/log.txt)

当前的建议：

1. 附上可build该项目的开发环境的版本

2. 在`hoj-vue/.gitignore`里面添加一行：

```
package-lock.json
```

避免坑其它开发者

**Comment by HimitZH** [comment]
node版本太高导致的，最高版本不超过v16，建议用v14

**Comment by XY0797** [comment]
已提交pr，为vue项目的readme添加额外说明
