### ISSUE TITLE
用户在IPv6环境下提交题目出现500错误及解决办法

### ISSUE THREAD

**Issue by dbsan2333** [HimitZH/HOJ#65]
在提交时发现出现500 Server Error，可以通过`docker logs hoj-backend`查看后端服务日志。如果出现
> Data truncation: Data too long for column 'ip' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ip' at row 1

则基本上可以判断为由于IPv6地址超出`ip`字段长度导致无法成功插入数据。

### 解决办法：
使用root账号连接mysql，进入`hoj`数据库，修改`judge`表`ip`字段的数据类型即可：
`ALTER TABLE judge MODIFY ip  varchar(45)`

btw：我后来又排查了其他表，发现在`judge_server`和`session`表中也有`ip`字段，但长度设置的是255，不知道有没有其他用意，我暂时改成45了，后面观察观察（

**Comment by HimitZH** [comment]
judge_server和session表长度默认是255并无特别设计，judge表的IP字段确实有这个bug，已收到建议，我会尽快修复

**Comment by HimitZH** [comment]
已修复，最新版本的hoj-mysql-checker会自动更新

**Comment by HimitZH** [comment]
更新分支：[ad904c](https://github.com/HimitZH/HOJ/commit/ad904c3353988dbffecf757405b0485d4e383a5c)
