### ISSUE TITLE
judge.token未刷新

### ISSUE THREAD

**Issue by Graypigeonhgh** [HimitZH/HOJ#66]
请问这个judge.token是固定的吗，为什么我一直不能刷新token

![屏幕截图 2024-08-02 121815](https://github.com/user-attachments/assets/4747e357-c3ce-487d-bcee-62165c257b27)

**Comment by HimitZH** [comment]
非固定，如果是配置文件默认是default，那么每次重启后端服务都会刷新

**Comment by Graypigeonhgh** [comment]
好的感谢
