### ISSUE TITLE
代码编译报错SystemError

### ISSUE THREAD

**Issue by huang-676** [HimitZH/HOJ#67]
该项目在本地调试，go-judge路径为云端，提交测评时报错
![image](https://github.com/user-attachments/assets/68fde113-b8ce-4d31-a773-5520a887737d)

**Comment by Graypigeonhgh** [comment]
File.separator在 windows 上是反斜杠 \，在 Linux 上是正斜杠 /

**Comment by HimitZH** [comment]
go-judge运行到环境得有题目的测试数据文件，也就是hoj-judgeserver和go-judge要跑在一个环境，同时题目数据得在这机器上，所以hoj-judgesever一般不能本地调试评测
