### ISSUE TITLE
优化建议：后端返回前端建议使用DAO

### ISSUE THREAD

**Issue by Yerosius** [HimitZH/HOJ#76]
如题，目前使用的是VO

**Comment by HimitZH** [comment]
你是不是理论学错了，DAO是数据源（数据库）查询出来转化的java对象类，而VO用于表示用户界面（前端）上显示的数据

**Comment by HimitZH** [comment]
你是不是理论学错了，DAO是要访问数据源（数据库）进行查询等操作传输的java对象类，而VO用于表示用户界面（前端）上显示的数据
